### ISSUE TITLE
GLDF  adding signatures

### ISSUE THREAD

**Issue by chmeis** [globallightingdata/gldf#24]
I have been searching the gldf docs for hints for how to implement signatures, since it would be very desirable for us to create gldf files we can verify as coming from us. What I found was only a short statement here:
https://gldf.io/docs/container/container-specification
https://gldf.io/docs/container/meta-information

Is there anything else? Is a more detailed spec on the roadmap? Thanks!

**Comment by holg** [comment]
Well this is some basic stuff to do, even so, it takes some time to implement, but I'd assume this is something, you might need to contract, or do it yourself.

Here is how you can achieve it, keep in mind you need the control, but as well want others being able to verify, not you alone!

E.g. you can use OpenSSL, to create the signature:

So here is how to do, just some basic Linux Commands:

First create the private.key (which you need to save safely, and keep private)

`openssl genrsa -out privatekey.pem 2048 `

Now you can Crete the signature of a GLDF file:

`openssl dgst -sha256 -sign privatekey.pem -out test.gldf.signature test.gldf`

This test.gldf.signature, is not the good format to put inside the XML file, so we do the BASE64 of it:

`base64 < test.gldf.signature`

e.g.:
`vMKM3qMf/VQfUnwvalomDssjXqSyMd+YkK3e9xxTnGh3cEWdWOrEPQukvQw3v+gRmVhmHMZJP55ALXPoXtk1yrl4HwrcP9ySXwNrJH/ZtI9JXjbvTp7qU9p4u8B7vdYBG5bqIMKXT7wTZdLPsXZVHHaIo3PKAh+uTQgcbQrkwtc4PGhugTc+XP0WyvLpm33V2cbcKe6mbJsLegBkRexY0tFVDuoUSE1Ls9SrzV2TysoQcDovBdn6s10j2S2Wiafuhh5BXz5ASSXy1tyalbIZLwGpj7nWMm+OKQ8MCLpcB/Vnohb5DA5xTOKmz2I2ggw9YIUsU536vC/JN0pdBx/3fQ==`

This you could put inside of the  `meta-information.xml`

E.g.

`<MetaInformation>
  <Property name="XAL-test-Signature">vMKM3qMf/VQfUnwvalomDssjXqSyMd+YkK3e9xxTnGh3cEWdWOrEPQukvQw3v+gRmVhmHMZJP55ALXPoXtk1yrl4HwrcP9ySXwNrJH/ZtI9JXjbvTp7qU9p4u8B7vdYBG5bqIMKXT7wTZdLPsXZVHHaIo3PKAh+uTQgcbQrkwtc4PGhugTc+XP0WyvLpm33V2cbcKe6mbJsLegBkRexY0tFVDuoUSE1Ls9SrzV2TysoQcDovBdn6s10j2S2Wiafuhh5BXz5ASSXy1tyalbIZLwGpj7nWMm+OKQ8MCLpcB/Vnohb5DA5xTOKmz2I2ggw9YIUsU536vC/JN0pdBx/3fQ==</Property>
  <Property name="ExampleLLC-Signature">5437af9d-18c4-485e-b396-1d3d6531fb29</Property>
</MetaInformation>
`

to verify the base64 encoded signature, you need to have the public key, which is OK, because this one you can give out to your clients:

`openssl rsa -in privatekey.pem -outform PEM -pubout -out publickey.pem`


`echo "vMKM3qMf/VQfUnwvalomDssjXqSyMd+YkK3e9xxTnGh3cEWdWOrEPQukvQw3v+gRmVhmHMZJP55ALXPoXtk1yrl4HwrcP9ySXwNrJH/ZtI9JXjbvTp7qU9p4u8B7vdYBG5bqIMKXT7wTZdLPsXZVHHaIo3PKAh+uTQgcbQrkwtc4PGhugTc+XP0WyvLpm33V2cbcKe6mbJsLegBkRexY0tFVDuoUSE1Ls9SrzV2TysoQcDovBdn6s10j2S2Wiafuhh5BXz5ASSXy1tyalbIZLwGpj7nWMm+OKQ8MCLpcB/Vnohb5DA5xTOKmz2I2ggw9YIUsU536vC/JN0pdBx/3fQ==" | base64 -d -o test.signature`

openssl dgst -sha256 -verify publickey.pem -signature  test.signature test.gldf`
Verified OK

So this it is basically, but keep in mind:
you need to test the signature against the GLDf File, without the meta-information.xml,
as it is a chicken-egg situation, as the meta-information.xml will change the signature, because you need to do it without it...

**Comment by chmeis** [comment]
Thank you! for the quick answer.  The real question, do we want to specify something standardised. Something that could be extended to verify a chain of trust to root certificates, maybe held by RELUX and Dialux. There appear to be standards for that. Like in http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part3.html

What I find interesting with OASIS is, that they would sign the assets in the package individually, seems like an elegant way to do it.

But, I take away, you are not aware of any effort to create a standard for signing gldf?

**Comment by holg** [comment]
Well I do not think it is appropriate, to hand out the liability to verify to Dialux and RELUX alone.
Therefore I proposed some standard way, which gives that liability to the instance, which creates the GLDF, which is you in this case.
The same way I proposed to do could as well be done signing each use individually,
this in deed might even be better, because you could verify the GLDF without needing to push out meta-information.xml.

I am not aware of any effort in creating a standard for signing gldf.

**Comment by tkock-dx** [comment]
Actually RELUX as well as DIALux are planning to provide a solution for manufacturers for signing and validating GLDF files. Even if there is no time schedule yet, you may contact RELUX and/or DIALux for any details. Of course, we will make a public announcement as soon as we have more concrete information about this topic.

**Comment by holg** [comment]
I created the rust crate for this purpose, it uses the very well respected minisign and my crate gldf_rs.
[gldf-sign](https://crates.io/crates/gldf-sign)
easy to install and Open Source

**Comment by Kurpanik** [comment]
This solution on its own is like self-signed certificates for the web. It's missing the trusted third party issuing some secret (in your case a certificate authority) - trusted by the manufacturer as well as the party relying upon it, the GLDF user. And has therefore the same limited use case - where the issuer and the user are the same entity.

**Comment by holg** [comment]
OK, the simple solution would be to include the SSL public key, issued by the 3rd Party entity in the trusted comment section, but we need to keep in mind, that 3rd party issued certificates expire at some point,
this could be checked as well et voilá...

**Comment by Kurpanik** [comment]
And the user would simply check the gldf with your library?

**Comment by holg** [comment]
Well yes, it is OpenSource, if I find some time, I could configure GitHub to do Release builds for any kid of platform.
Without this, so right now, it is quite easy to install as well:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
`cargo install gldf-sign`
Right now it is a CLI tool, but as Library (the verify part), I could as well build as WebAssembly,
or of course the lib could be used for any kind of software, which links to it...
