### ISSUE TITLE
Special characters in names

### ISSUE THREAD

**Issue by sandra-prolicht** [globallightingdata/gldf#26]
How should we handle special characters in names? We frequently have °, Ø and () in luminare product names. Most characters do not break the gldf, but parenthesis do. I tried to escape it with it's html equivalent (&#40;  and &#41;) but the file still does not load in Relux. I did not see any restrictions in schema or on gldf.io. Should we just replace those chars with a dot and if so what chars could be problematic?

**Comment by Kurpanik** [comment]
Hello Sandra, parenthesis should be indeed escaped in XML. As follows:

```
< as &lt;
> as &gt;
( as &#40; 
) as &#41;
```

Update:
 ( and ) can, but must not be escaped.

**Comment by sandra-prolicht** [comment]
Thanks for your quick response. I thought so!

**Comment by Kurpanik** [comment]
You're welcome!

**Comment by prolicht-at** [comment]
@Kurpanik why do we need to escape normal characters?

In XML, only those characters need to be escaped:

 - `"`  should be `&quot;`
 - `'`   should be `&apos;`
 - `<`   should be `&lt;`
 - `>`   should be `&gt;`
 - `&`   should be `&amp;`

So GLDF should follow this standard.

**Comment by Kurpanik** [comment]
Yes, you are right. Brackets of type ( and ) do not need to be escaped as XML content. And since GLDF is based on XML, the same applies here. In DIALux, there are no problems with this. This brackets are accepted both escaped and unescaped. If Relux behaves incorrectly in this regard, I recommend contacting their support team.

**Comment by prolicht-at** [comment]
Thanks for the clarification!
