### ISSUE TITLE
Photometry XSD Definition

### ISSUE THREAD

**Issue by mrmonat** [globallightingdata/gldf#7]
The choice element doesn't seem correct (or at the correct position) in the xsd definition for a photometry.

Should it be possible to specify a `PhotometryFileReference` OR (`Rotation-G0` AND `DescriptivePhotometry`) or should it be possible to specify a `PhotometryFileReference` AND `Rotation-G0` AND `DescriptivePhotometry`?

![Bildschirmfoto 2021-06-10 um 12 22 53](https://user-images.githubusercontent.com/17597850/121509275-c59d1800-c9e6-11eb-991f-cc7b42bb640a.png)

**Comment by Kurpanik** [comment]
Hi Luca, a good question because the xsd:choice seems indeed to be unnecessary at the moment.

The current logic is: 

- A mandatory `PhotometryFileReference`
- AND optional: `Rotation-G0` AND/OR `DescriptivePhotometry`

The choice element beforehand `PhotometryFileReference` is a preparation for a possible extension in the future: The possibility to provide photometric intensity distributions directly inside the gldf xml INSTEAD of an external file reference on Eulumdat or IES. 

So a possible logic in the future could be: 

- A mandatory `PhotometryFileReference` OR a mandatory `IntensityDistribution` collection
- AND optional `Rotation-G0` AND/OR `DescriptivePhotometry`

**Comment by mrmonat** [comment]
Thanks for the clarification :)
